---
title: "Phylo Sim density dependence"
format: html
editor: visual
---

```{r}
#| warning: false
  
library(PhyloSim)
```

### define params and run model

```{r}
#| eval: true
#| echo: false

sort(c((rep(1:50 * 50) + 1), rep(1:50 * 50)))

par1 <- createCompletePar(x = 256,
                         y = 256,
                         dispersal = 1,
                         runs = sort(c((rep(1:2000 * 50) + 1), rep(1:2000 * 50))),
                         specRate = 2,
                         density = 1, # NDD (but not Conspecific)
                         environment = 0,
                         fitnessActsOn = "mortality",
                         fitnessBaseMortalityRatio = 1, 
                         densityCut = 1,
                         seed = 20250414,
                         type = "base",
                         protracted = 0,
                         fission = 0,
                         redQueen = 0,
                         redQueenStrength = 0,
                         airmat = NA,
                         scenario = "dd_1")

simu <- runSimulation(par1)
```

```{r}
#| eval: true
#| echo: false

saveRDS(simu, "/home/andy/cyber_synch/local/runs/20250414_dd_1")
```

```{r}
tst <- readRDS("~/Uni/Master/MA/local/runs/fat/20250414_dd_1")
```

### Access results
#### Spatial distribution
```{r}
#| fig-width: 2.5
#| fig-height: 3

simu_4000 <- simu$Output[[4000]] # simulation step 100001, i.e., last model output
image(simu_4000$specMat)
```

#### Species richness

```{r}
spec_time(sim_out = tst, thinning_factor = 3)
spec_time(sim_out = tst, thinning_factor = 10)
```

#### Species abundance

```{r}
abundance
PhyloSim::rac(simu, plot = "bar", which.result = 4000)
PhyloSim::rac(simu, plot = "line", which.result = "all")
```

