---
title: "Phylo Sim null model"
format: html
editor: visual
---

### load packages and choose number of cores

```{r}
#| warning: false
  
library(PhyloSim)
library(parallel)

nCores <- detectCores()

```

### define params

```{r}

par1 <- createCompletePar(x = 100,
                         y = 100,
                         dispersal = "global",
                         runs = c(1,2, 10,11, 100,101, 1000,1001
                                  # 100000,100001, 200000,200001, 300000,300001
                                  # 400000,400001, 500000,500001, 600000,600001
                                  ),
                         specRate = 2,
                         density = 1, # NDD (but not Conspecific)
                         environment = 0,
                         fitnessActsOn = "mortality",
                         fitnessBaseMortalityRatio = 1, # equal traits -> mortality
                         densityCut = FALSE,
                         seed = 20250408,
                         type = "base",
                         protracted = 0,
                         fission = 0,
                         redQueen = 0,
                         redQueenStrength = 0,
                         airmat = NA,
                         scenario = "null")
```

### run model in parallel

```{r}
res <- runSimulation(par1)
```

```{r}
print(system.time(core20 <- mclapply(list(par1, par1, par1), FUN=runSimulation, mc.cores=2)))
```
