---
title: "Phylo Sim density dependence"
format: html
editor: visual
---

```{r}
#| warning: false
  
library(PhyloSim)
```

### define params and run model

```{r}
#| eval: true
#| echo: false

sort(c((rep(1:50 * 50) + 1), rep(1:50 * 50)))

par1 <- createCompletePar(x = 256,
                         y = 256,
                         dispersal = 1,
                         runs = sort(c((rep(1:2000 * 50) + 1), rep(1:2000 * 50))),
                         specRate = 2,
                         density = 1, # NDD (but not Conspecific)
                         environment = 0,
                         fitnessActsOn = "mortality",
                         fitnessBaseMortalityRatio = 1, 
                         densityCut = 1,
                         seed = 20250414,
                         type = "base",
                         protracted = 0,
                         fission = 0,
                         redQueen = 0,
                         redQueenStrength = 0,
                         airmat = NA,
                         scenario = "dd_1")
par2 <- createCompletePar(x = 256,
                         y = 256,
                         dispersal = 1,
                         runs =rep(1:10 * 10),
                         specRate = 2,
                         density = 1, # NDD (but not Conspecific)
                         environment = 0,
                         fitnessActsOn = "both",
                         fitnessBaseMortalityRatio = 1, 
                         densityCut = 1,
                         seed = 20250414,
                         type = "base",
                         protracted = 0,
                         fission = 0,
                         redQueen = 0,
                         redQueenStrength = 0,
                         airmat = NA,
                         scenario = "dd_1")

simu <- runSimulation(par2)
```

```{r}
#| eval: true
#| echo: false

saveRDS(simu, "/home/andy/cyber_synch/local/runs/20250414_dd_1")
```

```{r}
#| echo: false

# simu <- readRDS("/home/andy/cyber_synch/local/runs/20250414_dd_1")
simu <- readRDS("~/Uni/Master/MA/local/runs/20250414_dd_1")
```

### Access results

#### Parameter settings 
```{r}
simu$Model
```
```{r}
(simu$Model$runtime / 3600) * 14
```
```{r}
str(simu$Output[[4000]])
image(simu$Output[[4000]]$specMat == simu$Output[[3999]]$specMat)
image(simu$Output[[4000]]$specMat)
image(simu$Output[[4000]]$compMat)
image(simu$Output[[4000]]$envMat)
```


#### Spatial distribution

```{r}
#| fig-width: 2.5
#| fig-height: 3

simu_4000 <- simu$Output[[4000]] # simulation step 100001, i.e., last model output
image(simu_4000$specMat)
```


#### Species richness

```{r}
sr_simu <- sapply(1:4000, function(x) PhyloSim::specRich(simu = simu, which.result = x))
plot(sr_simu, type = "l")
```

#### Species abundance

```{r}
PhyloSim::rac(simu, plot = "bar", which.result = 4000)
PhyloSim::rac(simu, plot = "line", which.result = "all")
```


### visualize results

```{r}
#| label: fig-spatial_distirbution
#| fig-width: 5
#| fig-height: 5

plotSpatialPhylo(simu, which.result = 100)
plotSpatialPhylo(simu, which.result = 200)
plotSpatialPhylo(simu, which.result = 300)
plotSpatialPhylo(simu, which.result = 400)
plotSpatialPhylo(simu, which.result = 500)
plotSpatialPhylo(simu, which.result = 600)
plotSpatialPhylo(simu, which.result = 700)
plotSpatialPhylo(simu, which.result = 800)
plotSpatialPhylo(simu, which.result = 900)
plotSpatialPhylo(simu, which.result = 1000)
plotSpatialPhylo(simu, which.result = 1100)
plotSpatialPhylo(simu, which.result = 1200)
plotSpatialPhylo(simu, which.result = 1300)
plotSpatialPhylo(simu, which.result = 1400)
plotSpatialPhylo(simu, which.result = 1500)
plotSpatialPhylo(simu, which.result = 1600)
plotSpatialPhylo(simu, which.result = 1700)
plotSpatialPhylo(simu, which.result = 1800)
plotSpatialPhylo(simu, which.result = 1900)
plotSpatialPhylo(simu, which.result = 2000)
plotSpatialPhylo(simu, which.result = 4000)

```

```{r}
#| label: fig-spatial_distirbution
#| fig-width: 5
#| fig-height: 5
#| fig-cap:
#|   - Spatial distribution at step 1
#|   - Spatial distribution at step 2
#|   - Spatial distribution at step 10
#|   - Spatial distribution at step 11
#|   - Spatial distribution at step xx
#|   - Spatial distribution at step xx
#|   - Spatial distribution at step xx
#|   - Spatial distribution at step xx
#|   - Spatial distribution at step xx
#|   - Spatial distribution at step xx
#|   - Spatial distribution at step xx
#|   - Spatial distribution at step xx
#|   - Spatial distribution at step xx
#|   - Spatial distribution at step xx
#|   - Spatial distribution at step xx
#|   - Spatial distribution at step xx
#|   - Spatial distribution at step xx
#|   - Spatial distribution at step xx
#|   - Spatial distribution at step xx
#|   - Spatial distribution at step xx
#|   - Spatial distribution at step xx
#|   - Spatial distribution at step xx


# plotSpatialPhylo(simu, which.result = 1)
# plotSpatialPhylo(simu, which.result = 2)
# plotSpatialPhylo(simu, which.result = 3)
# plotSpatialPhylo(simu, which.result = 4)
# plotSpatialPhylo(simu, which.result = 5)
# plotSpatialPhylo(simu, which.result = 6)
# plotSpatialPhylo(simu, which.result = 7)
# plotSpatialPhylo(simu, which.result = 8)
# plotSpatialPhylo(simu, which.result = 9)
# plotSpatialPhylo(simu, which.result = 10)
# plotSpatialPhylo(simu, which.result = 10)
# plotSpatialPhylo(simu, which.result = 11)
# plotSpatialPhylo(simu, which.result = 12)
# plotSpatialPhylo(simu, which.result = 13)
# plotSpatialPhylo(simu, which.result = 14)
# plotSpatialPhylo(simu, which.result = 15)
# plotSpatialPhylo(simu, which.result = 16)
# plotSpatialPhylo(simu, which.result = 17)
# plotSpatialPhylo(simu, which.result = 18)
# plotSpatialPhylo(simu, which.result = 19)
# plotSpatialPhylo(simu, which.result = 20)
# plotSpatialPhylo(simu, which.result = 21)
# plotSpatialPhylo(simu, which.result = 22)
```
