---
title: "Phylo Sim density dependence"
format: html
editor: visual
---

```{r}
#| warning: false
  
library(PhyloSim)
library(parallel)
```

### define params and run model

```{r}
#| eval: true
#| echo: false

par1 <- createCompletePar(x = 256,
                          y = 256,
                          density = 1,
                          dispersal = 1,
                          specRate = 2,
                          environment = 0,
                          fitnessBaseMortalityRatio = 1, 
                          densityCut = 1,
                          seed = 20250414,
                          type = "base",
                          protracted = 0,
                          fission = 0,
                          redQueen = 0,
                          redQueenStrength = 0,
                          airmat = NA,
                          scenario = "dd1_disp1_sr2_e0_m1_cut1")

par2 <- createCompletePar(x = 256,
                          y = 256,
                          density = 1,
                          dispersal = 5,
                          specRate = 2,
                          environment = 0,
                          fitnessBaseMortalityRatio = 1, 
                          densityCut = 1,
                          seed = 20250414,
                          type = "base",
                          protracted = 0,
                          fission = 0,
                          redQueen = 0,
                          redQueenStrength = 0,
                          airmat = NA,
                          scenario = "dd1_disp5_sr2_e0_m1_cut1")

par3 <- createCompletePar(x = 256,
                          y = 256,
                          density = 1,
                          dispersal = 10,
                          specRate = 2,
                          environment = 0,
                          fitnessBaseMortalityRatio = 1, 
                          densityCut = 1,
                          seed = 20250414,
                          type = "base",
                          protracted = 0,
                          fission = 0,
                          redQueen = 0,
                          redQueenStrength = 0,
                          airmat = NA,
                          scenario = "dd1_disp10_sr2_e0_m1_cut1")

par4 <- createCompletePar(x = 256,
                          y = 256,
                          density = 0,
                          dispersal = 1,
                          specRate = 2,
                          environment = 0,
                          fitnessBaseMortalityRatio = 1, 
                          densityCut = 1,
                          seed = 20250414,
                          type = "base",
                          protracted = 0,
                          fission = 0,
                          redQueen = 0,
                          redQueenStrength = 0,
                          airmat = NA,
                          scenario = "dd0_disp1_sr2_e0_m1_cut1")

par5 <- createCompletePar(x = 256,
                          y = 256,
                          density = 0.5,
                          dispersal = 1,
                          specRate = 2,
                          environment = 0,
                          fitnessBaseMortalityRatio = 1, 
                          densityCut = 1,
                          seed = 20250414,
                          type = "base",
                          protracted = 0,
                          fission = 0,
                          redQueen = 0,
                          redQueenStrength = 0,
                          airmat = NA,
                          scenario = "dd0-5_disp1_sr2_e0_m1_cut1")

par6 <- createCompletePar(x = 256,
                          y = 256,
                          density = 1.5,
                          dispersal = 1,
                          specRate = 2,
                          environment = 0,
                          fitnessBaseMortalityRatio = 1, 
                          densityCut = 1,
                          seed = 20250414,
                          type = "base",
                          protracted = 0,
                          fission = 0,
                          redQueen = 0,
                          redQueenStrength = 0,
                          airmat = NA,
                          scenario = "dd1-5_disp1_sr2_e0_m1_cut1")

par7 <- createCompletePar(x = 256,
                          y = 256,
                          density = 1,
                          dispersal = 1,
                          specRate = 1,
                          environment = 0,
                          fitnessBaseMortalityRatio = 1, 
                          densityCut = 1,
                          seed = 20250414,
                          type = "base",
                          protracted = 0,
                          fission = 0,
                          redQueen = 0,
                          redQueenStrength = 0,
                          airmat = NA,
                          scenario = "dd1_disp1_sr1_e0_m1_cut1")

par8 <- createCompletePar(x = 256,
                          y = 256,
                          density = 1,
                          dispersal = 1,
                          specRate = 3,
                          environment = 0,
                          fitnessBaseMortalityRatio = 1, 
                          densityCut = 1,
                          seed = 20250414,
                          type = "base",
                          protracted = 0,
                          fission = 0,
                          redQueen = 0,
                          redQueenStrength = 0,
                          airmat = NA,
                          scenario = "dd1_disp1_sr3_e0_m1_cut1")

par9 <- createCompletePar(x = 256,
                          y = 256,
                          density = 1,
                          dispersal = 1,
                          specRate = 4,
                          environment = 0,
                          fitnessBaseMortalityRatio = 1, 
                          densityCut = 1,
                          seed = 20250414,
                          type = "base",
                          protracted = 0,
                          fission = 0,
                          redQueen = 0,
                          redQueenStrength = 0,
                          airmat = NA,
                          scenario = "dd1_disp1_sr4_e0_m1_cut1")

par10 <- createCompletePar(x = 256,
                           y = 256,
                           density = 1,
                           dispersal = 1,
                           specRate = 2,
                           environment = 0,
                           fitnessBaseMortalityRatio = 2, 
                           densityCut = 2,
                           seed = 20250414,
                           type = "base",
                           protracted = 0,
                           fission = 0,
                           redQueen = 0,
                           redQueenStrength = 0,
                           airmat = NA,
                           scenario = "dd1_disp1_sr2_e0_m1_cut2")

par11 <- createCompletePar(x = 256,
                           y = 256,
                           density = 1,
                           dispersal = 1,
                           specRate = 2,
                           environment = 0,
                           fitnessBaseMortalityRatio = 1, 
                           densityCut = 3,
                           seed = 20250414,
                           type = "base",
                           protracted = 0,
                           fission = 0,
                           redQueen = 0,
                           redQueenStrength = 0,
                           airmat = NA,
                           scenario = "dd1_disp1_sr1_e0_m1_cut3")

par12 <- createCompletePar(x = 256,
                           y = 256,
                           density = 1,
                           dispersal = 1,
                           specRate = 2,
                           environment = 0,
                           fitnessBaseMortalityRatio = 2, 
                           densityCut = 1,
                           seed = 20250414,
                           type = "base",
                           protracted = 0,
                           fission = 0,
                           redQueen = 0,
                           redQueenStrength = 0,
                           airmat = NA,
                           scenario = "dd1_disp1_sr1_e0_m2_cut3")

par13 <- createCompletePar(x = 256,
                           y = 256,
                           density = 1,
                           dispersal = 1,
                           specRate = 2,
                           environment = 0,
                           fitnessBaseMortalityRatio = 3, 
                           densityCut = 1,
                           seed = 20250414,
                           type = "base",
                           protracted = 0,
                           fission = 0,
                           redQueen = 0,
                           redQueenStrength = 0,
                           airmat = NA,
                           scenario = "dd1_disp1_sr1_e0_m3_cut3")

par14 <- createCompletePar(x = 256,
                           y = 256,
                           density = 1,
                           dispersal = 1,
                           specRate = 2,
                           environment = 0,
                           fitnessBaseMortalityRatio = 4, 
                           densityCut = 1,
                           seed = 20250414,
                           type = "base",
                           protracted = 0,
                           fission = 0,
                           redQueen = 0,
                           redQueenStrength = 0,
                           airmat = NA,
                           scenario = "dd1_disp1_sr1_e0_m4_cut3")


params <- list(par1, par2, par3, par4, par5, par6, par7, par8, par9, par10,
               par11, par12, par13, par14)
```

```{r}
simu <- runSimulationBatch(params, parallel = 40)
save_out(simu, path = "~/Uni/MAster/MA/local/runs/slim/", batch = TRUE, slim = TRUE)
```

