---
title: "fbmr"
author: "ai"
format: html
editor: visual
---

# load
```{r}
#| warning: false
library(PhyloSim)
# source("~/cyber_synch/git_synch/scripts/functions.R")
source("~/Uni/Master/MA/git_synch/scripts/functions.R")
```

```{r}
runs <- readRDS("~/cyber_synch/local/runs/fat/20250520_mortality")
```

```{r}
namelist <- numeric()
for (i in 1:length(runs)) {
  name <- paste0(
    "dd",
    (ifelse(runs[[i]]$Model$density == TRUE, "T", "F")),
    "_cs",
    runs[[i]]$Model$compStrength,
    "_disp",
    (ifelse(!is.numeric(runs[[i]]$Model$dispersal), "G", runs[[i]]$Model$dispersal)),
    "_cut",
    runs[[i]]$Model$densityCut,
    "_fbmr",
    runs[[i]]$Model$fitnessBaseMortalityRatio
  )
  namelist[i] <- name
}

mat_list <- list()
for (i in 1:length(runs)) {
  mat_list[[i]] <- runs[[i]]$Output[[20]]$specMat
}
names(mat_list) <- namelist

# only differences are between disp1 and dispG
sum(mat_list[["ddT_cs1_disp1_cut1"]] != mat_list[["ddT_cs1_disp4_cut1"]])
sum(mat_list[["ddT_cs1_disp1_cut1"]] != mat_list[["ddT_cs1_dispG_cut1"]])
sum(mat_list[["ddT_cs1_disp4_cut1"]] != mat_list[["ddT_cs1_dispG_cut1"]])

sum(mat_list[["ddF_cs1_disp1_cut1"]] != mat_list[["ddF_cs1_dispG_cut1"]])
sum(mat_list[["ddF_cs1_disp1_cut1"]] != mat_list[["ddF_cs1_dispG_cut2"]])

sum(mat_list[["ddF_cs1_disp1_cut1"]] != mat_list[["ddT_cs1_dispG_cut1"]])
sum(mat_list[["ddF_cs1_disp1_cut1"]] != mat_list[["ddT_cs1_dispG_cut2"]])
sum(mat_list[["ddF_cs1_disp1_cut1"]] != mat_list[["ddT_cs2_disp1_cut1"]])
sum(mat_list[["ddF_cs1_disp1_cut1"]] != mat_list[["ddT_cs2_disp1_cut2"]])
sum(mat_list[["ddF_cs1_disp1_cut1"]] != mat_list[["ddT_cs2_dispG_cut1"]])
sum(mat_list[["ddF_cs1_disp1_cut1"]] != mat_list[["ddT_cs2_dispG_cut2"]])
```

densityCut makes no difference at all. density(0,1) only differ in global scenario, however, no difference in cut

```{r}
sum(mat_list[["ddF_disp1_cut1_fbmr1"]] != mat_list[["ddF_disp1_cut1_fbmr10"]])



sum(mat_list$ddF1_disp1_cut1_fbmr1 != mat_list$ddT1_disp1_cut1_fbmr1)
sum(mat_list$ddF1_disp1_cut1_fbmr1 != mat_list$ddT2_disp1_cut1_fbmr1)
sum(mat_list$ddT1_disp1_cut1_fbmr1 != mat_list$ddT2_disp1_cut1_fbmr1)

sum(mat_list$ddF1_disp1_cut1_fbmr10 != mat_list$ddT1_disp1_cut1_fbmr10)
sum(mat_list$ddF1_disp1_cut1_fbmr10 != mat_list$ddT2_disp1_cut1_fbmr10) # this is weird: while ddF != ddT1, ddF == ddT2
sum(mat_list$ddT1_disp1_cut1_fbmr10 != mat_list$ddT2_disp1_cut1_fbmr10)

sum(mat_list$ddF1_dispG_cut1_fbmr1 != mat_list$ddT1_dispG_cut1_fbmr1)
sum(mat_list$ddF1_dispG_cut1_fbmr1 != mat_list$ddT2_dispG_cut1_fbmr1)
sum(mat_list$ddT1_dispG_cut1_fbmr1 != mat_list$ddT2_dispG_cut1_fbmr1)

sum(mat_list$ddF1_dispG_cut1_fbmr10 != mat_list$ddT1_dispG_cut1_fbmr10)
sum(mat_list$ddF1_dispG_cut1_fbmr10 != mat_list$ddT2_dispG_cut1_fbmr10) # this is weird: while ddF != ddT1, ddF == ddT2
sum(mat_list$ddT1_dispG_cut1_fbmr10 != mat_list$ddT2_dispG_cut1_fbmr10)

sum(mat_list[["ddF_disp1_cut1_fbmr1"]] != mat_list[["ddF_disp1_cut2_fbmr10"]]) # cut param still no difference
sum(mat_list[["ddF_disp1_cut1_fbmr1"]] != mat_list[["ddF_dispG_cut1_fbmr1"]])
sum(mat_list[["ddF_disp1_cut1_fbmr1"]] != mat_list[["ddF_dispG_cut2_fbmr1"]]) # cut param still no difference
sum(mat_list[["ddF_disp1_cut1_fbmr1"]] != mat_list[["ddF_dispG_cut1_fbmr10"]])
sum(mat_list[["ddF_disp1_cut1_fbmr1"]] != mat_list[["ddT_disp1_cut1_fbmr1"]])
sum(mat_list[["ddF_disp1_cut1_fbmr1"]] != mat_list[["ddT_disp1_cut1_fbmr10"]])
sum(mat_list[["ddF_disp1_cut1_fbmr1"]] != mat_list[["ddT_dispG_cut1_fbmr1"]])
sum(mat_list[["ddF_disp1_cut1_fbmr1"]] != mat_list[["ddT_dispG_cut1_fbmr10"]])

sum(mat_list[["ddF_disp1_cut1_fbmr1"]] != mat_list[["ddT_disp1_cut1_fbmr10"]])
sum(mat_list[["ddF_disp1_cut1_fbmr1"]] != mat_list[["ddT_disp1_cut1_fbmr1"]])
# there is a difference between density on and off only when fbmr > 1!

sum(mat_list[["ddF_dispG_cut1_fbmr1"]] != mat_list[["ddT_dispG_cut1_fbmr10"]])
sum(mat_list[["ddF_dispG_cut1_fbmr1"]] != mat_list[["ddT_dispG_cut1_fbmr1"]])
# in the global case there is a difference even when fbmr == 1
```

## plot fbmr \| dispersal

```{r}
#| fig-width: 10
#| fig-height: 5

par(mfrow = c(1,2))

image(mat_list$ddF1_disp1_cut1_fbmr1, main = "ddF1_disp1_cut1_fbmr1")
image(mat_list$ddF1_disp1_cut1_fbmr1, main = "ddF1_disp1_cut1_fbmr1")

image(mat_list$ddF_disp1_cut1_fbmr10, main = "ddF_disp1_cut1_fbmr10")

image(mat_list$ddF_disp1_cut2_fbmr1, main = "ddF_disp1_cut2_fbmr1")
image(mat_list$ddF_disp1_cut2_fbmr10, main = "ddF_disp1_cut2_fbmr10")

image(mat_list$ddF_dispG_cut1_fbmr1, main = "ddF_dispG_cut1_fbmr1")
image(mat_list$ddF_dispG_cut1_fbmr10, main = "ddF_dispG_cut1_fbmr10")

image(mat_list$ddF_dispG_cut2_fbmr1, main = "ddF_dispG_cut2_fbmr1")
image(mat_list$ddF_dispG_cut2_fbmr10, main = "ddF_dispG_cut2_fbmr10")
```

## plot dd \| dispersal

```{r}

#| fig-width: 15
#| fig-height: 5

par(mfrow = c(2,3))

# local cut1 fbmr1
image(mat_list$ddF1_disp1_cut1_fbmr1, main = "ddF1_disp1_cut1_fbmr1")
image(mat_list$ddT1_disp1_cut1_fbmr1, main = "ddT1_disp1_cut1_fbmr1")
image(mat_list$ddT2_disp1_cut1_fbmr1, main = "ddT2_disp1_cut1_fbmr1")
# local cut1 fbmr1
image(mat_list_start$ddF1_disp1_cut1_fbmr1, main = "Start: ddF1_disp1_cut1_fbmr1")
image(mat_list_start$ddT1_disp1_cut1_fbmr1, main = "Start: ddT1_disp1_cut1_fbmr1")
image(mat_list_start$ddT2_disp1_cut1_fbmr1, main = "Start: ddT2_disp1_cut1_fbmr1")

# local cut1 fbmr10
image(mat_list$ddF1_disp1_cut1_fbmr10, main = "ddF1_disp1_cut1_fbmr10")
image(mat_list$ddT1_disp1_cut1_fbmr10, main = "ddT1_disp1_cut1_fbmr10")
image(mat_list$ddT2_disp1_cut1_fbmr10, main = "ddT2_disp1_cut1_fbmr10")

# local cut1 fbmr10
image(mat_list_start$ddF1_disp1_cut1_fbmr10, main = "ddF1_disp1_cut1_fbmr10")
image(mat_list_start$ddT1_disp1_cut1_fbmr10, main = "ddT1_disp1_cut1_fbmr10")
image(mat_list_start$ddT2_disp1_cut1_fbmr10, main = "ddT2_disp1_cut1_fbmr10")

# local cut2 fbmr1
image(mat_list$ddF1_disp1_cut2_fbmr1, main = "ddF1_disp1_cut2_fbmr1")
image(mat_list$ddT1_disp1_cut2_fbmr1, main = "ddT1_disp1_cut2_fbmr1")
image(mat_list$ddT2_disp1_cut2_fbmr1, main = "ddT2_disp1_cut2_fbmr1")

# local cut2 fbmr1
image(mat_list_start$ddF1_disp1_cut2_fbmr1, main = "ddF1_disp1_cut2_fbmr1")
image(mat_list_start$ddT1_disp1_cut2_fbmr1, main = "ddT1_disp1_cut2_fbmr1")
image(mat_list_start$ddT2_disp1_cut2_fbmr1, main = "ddT2_disp1_cut2_fbmr1")

# local cut2 fbmr10
image(mat_list$ddF1_disp1_cut2_fbmr10, main = "ddF1_disp1_cut2_fbmr10")
image(mat_list$ddT1_disp1_cut2_fbmr10, main = "ddT1_disp1_cut2_fbmr10")
image(mat_list$ddT2_disp1_cut2_fbmr10, main = "ddT2_disp1_cut2_fbmr10")
# local cut2 fbmr10
image(mat_list_start$ddF1_disp1_cut2_fbmr10, main = "ddF1_disp1_cut2_fbmr10")
image(mat_list_start$ddT1_disp1_cut2_fbmr10, main = "ddT1_disp1_cut2_fbmr10")
image(mat_list_start$ddT2_disp1_cut2_fbmr10, main = "ddT2_disp1_cut2_fbmr10")

# global cut1 fbmr1
image(mat_list$ddF1_dispG_cut1_fbmr1, main = "ddF1_dispG_cut1_fbmr1")
image(mat_list$ddT1_dispG_cut1_fbmr1, main = "ddT1_dispG_cut1_fbmr1")
image(mat_list$ddT2_dispG_cut1_fbmr1, main = "ddT2_dispG_cut1_fbmr1")

# global cut1 fbmr1
image(mat_list_start$ddF1_dispG_cut1_fbmr1, main = "ddF1_dispG_cut1_fbmr1")
image(mat_list_start$ddT1_dispG_cut1_fbmr1, main = "ddT1_dispG_cut1_fbmr1")
image(mat_list_start$ddT2_dispG_cut1_fbmr1, main = "ddT2_dispG_cut1_fbmr1")

# global cut1 fbmr10
image(mat_list$ddF1_dispG_cut1_fbmr10, main = "ddF1_dispG_cut1_fbmr10")
image(mat_list$ddT1_dispG_cut1_fbmr10, main = "ddT1_dispG_cut1_fbmr10")
image(mat_list$ddT2_dispG_cut1_fbmr10, main = "ddT2_dispG_cut1_fbmr10")

# global cut1 fbmr10
image(mat_list_start$ddF1_dispG_cut1_fbmr10, main = "ddF1_dispG_cut1_fbmr10")
image(mat_list_start$ddT1_dispG_cut1_fbmr10, main = "ddT1_dispG_cut1_fbmr10")
image(mat_list_start$ddT2_dispG_cut1_fbmr10, main = "ddT2_dispG_cut1_fbmr10")

# global cut2 fbmr1
image(mat_list$ddF1_dispG_cut2_fbmr1, main = "ddF1_dispG_cut2_fbmr1")
image(mat_list$ddT1_dispG_cut2_fbmr1, main = "ddT1_dispG_cut2_fbmr1")
image(mat_list$ddT2_dispG_cut2_fbmr1, main = "ddT2_dispG_cut2_fbmr1")

# global cut2 fbmr1
image(mat_list_start$ddF1_dispG_cut2_fbmr1, main = "ddF1_dispG_cut2_fbmr1")
image(mat_list_start$ddT1_dispG_cut2_fbmr1, main = "ddT1_dispG_cut2_fbmr1")
image(mat_list_start$ddT2_dispG_cut2_fbmr1, main = "ddT2_dispG_cut2_fbmr1")

# global cut2 fbmr10
image(mat_list$ddF1_dispG_cut2_fbmr10, main = "ddF1_dispG_cut2_fbmr10")
image(mat_list$ddT1_dispG_cut2_fbmr10, main = "ddT1_dispG_cut2_fbmr10")
image(mat_list$ddT2_dispG_cut2_fbmr10, main = "ddT2_dispG_cut2_fbmr10")

# global cut2 fbmr10
image(mat_list_start$ddF1_dispG_cut2_fbmr10, main = "ddF1_dispG_cut2_fbmr10")
image(mat_list_start$ddT1_dispG_cut2_fbmr10, main = "ddT1_dispG_cut2_fbmr10")
image(mat_list_start$ddT2_dispG_cut2_fbmr10, main = "ddT2_dispG_cut2_fbmr10")

```

somehow cutoff works only if ddT = 1 not if ddT = 2. For local and global

densityCut makes no difference at all. density(0,1) only differ in global scenario, however, no difference in cut:
