---
title: "demo"
format: html
---

# load

```{r}
#| warning: false
library(PhyloSim)
library(parallel)
library(dplyr)
root <- "~/Uni/Master/MA/" # work from local machine
# root <- "~/cyber_synch/" # work from uni bayreuth server
# source("~/cyber_synch/git_synch/scripts/functions.R")
# source("~/Uni/Master/MA/git_synch/scripts/functions.R")
```

# params

```{r}
parNDD <- createCompletePar(x = 50, y = 50, type = "base",
                  dispersal = 1,
                  runs = sort(c(seq(100,5000,50),seq(100,5000,50)+1)),
                  negativeDensity = 1, nDensityCut = 1, nDDNicheWidth = .01,
                  positiveDensity = 0, 
                  specRate = 2,
                  fitnessActsOn = "mortality", fitnessBaseMortalityRatio = 10,
                  seed = 20250724,
                  scenario = "demo1")

parPDD <- createCompletePar(x = 50, y = 50, type = "base",
                  dispersal = 1,
                  runs = sort(c(seq(100,5000,50),seq(100,5000,50)+1)),
                  negativeDensity = 0,
                  positiveDensity = 1, pDensityCut = 1, pDDNicheWidth = .01, 
                  specRate = 2,
                  fitnessActsOn = "mortality", fitnessBaseMortalityRatio = 10,
                  seed = 20250724,
                  scenario = "demo2")

parBoth <- createCompletePar(x = 50, y = 50, type = "base",
                  dispersal = 1,
                  runs = sort(c(seq(100,5000,50),seq(100,5000,50)+1)),
                  negativeDensity = 1, nDensityCut = 1, nDDNicheWidth = .01,
                  positiveDensity = 1, pDensityCut = 1, pDDNicheWidth = .01, 
                  specRate = 2,
                  fitnessActsOn = "mortality", fitnessBaseMortalityRatio = 10,
                  seed = 20250724,
                  scenario = "demo3")

parNull <- createCompletePar(x = 50, y = 50, type = "base",
                  dispersal = 1,
                  runs = sort(c(seq(100,5000,50),seq(100,5000,50)+1)),
                  negativeDensity = 0,
                  positiveDensity = 0, 
                  specRate = 2,
                  fitnessActsOn = "mortality", fitnessBaseMortalityRatio = 10,
                  seed = 20250724,
                  scenario = "demo4")

parGlob <- createCompletePar(x = 50, y = 50, type = "base",
                  dispersal = "global",
                  runs = sort(c(seq(100,5000,50),seq(100,5000,50)+1)),
                  negativeDensity = 0,
                  positiveDensity = 0, 
                  specRate = 2,
                  fitnessActsOn = "mortality", fitnessBaseMortalityRatio = 10,
                  seed = 20250724,
                  scenario = "demo4")

parlist <- list(parNDD,parPDD, parBoth, parNull, parGlob)
```

# run

```{r}
simu1 <- runSimulationBatch(pars = parlist, parallel = 5)
```

# visualization

```{r}
names(simu1) <- getNames(simu1)

simu1 <- lapply(simu1, function(x) {
  names(x$Output) <- x$Model$runs
  return(x)
})

class(simu1) <- "PhylosimList"
```

## species matrix

```{r}
E <- matrix(c(2,2,2,2,2,
              2,0,0,0,0,
              2,0,0,0,0,
              2,2,2,2,0,
              2,0,0,0,0,
              2,0,0,0,0,
              2,2,2,2,2), nrow=7, byrow=TRUE)

A <- matrix(c(0,1,1,1,0,
              1,0,0,0,1,
              1,0,0,0,1,
              1,1,1,1,1,
              1,0,0,0,1,
              1,0,0,0,1,
              1,0,0,0,1), nrow=7, byrow=TRUE)

S <- matrix(c(0,4,4,4,4,
              4,0,0,0,0,
              4,0,0,0,0,
              0,4,4,4,0,
              0,0,0,0,4,
              0,0,0,0,4,
              4,4,4,4,0), nrow=7, byrow=TRUE)

I <- matrix(c(3,3,3,3,3,
              0,0,3,0,0,
              0,0,3,0,0,
              0,0,3,0,0,
              0,0,3,0,0,
              0,0,3,0,0,
              3,3,3,3,3), nrow=7, byrow=TRUE)

# Add spacing between letters (1 column of zeros)
space <- matrix(0, nrow=7, ncol=1)

# Combine letters with spacing
easi_matrix <- cbind(E, space, A, space, S, space, I)
```

```{r}
par(mfrow= c(2,3), mar=c(2,2,2,2))

image(simu1$pdd0_ndd1Var0.01Cut1_disp1_sr2_fbmr10_faoM$Output$`100`$specMat, main = "ndd_100")
image(simu1$pdd1Var0.01Cut1_ndd0_disp1_sr2_fbmr10_faoM$Output$`100`$specMat, main = "pdd_100")
image(simu1$pdd1Var0.01Cut1_ndd1Var0.01Cut1_disp1_sr2_fbmr10_faoM$Output$`100`$specMat, main = "both_100")
image(simu1$pdd0_ndd0_disp1_sr2_fbmr10_faoM$Output$`100`$specMat, main = "none_100")
image(simu1$pdd0_ndd0_dispG_sr2_fbmr10_faoM$Output$`100`$specMat, main = "glob_100")
image(easi_matrix, col = rainbow(5))

image(simu1$pdd0_ndd1Var0.01Cut1_disp1_sr2_fbmr10_faoM$Output$`101`$specMat, main = "ndd_101")
image(simu1$pdd1Var0.01Cut1_ndd0_disp1_sr2_fbmr10_faoM$Output$`101`$specMat, main = "pdd_101")
image(simu1$pdd1Var0.01Cut1_ndd1Var0.01Cut1_disp1_sr2_fbmr10_faoM$Output$`101`$specMat, main = "both_101")
image(simu1$pdd0_ndd0_disp1_sr2_fbmr10_faoM$Output$`101`$specMat, main = "none_101")
image(simu1$pdd0_ndd0_dispG_sr2_fbmr10_faoM$Output$`101`$specMat, main = "glob_101")
image(easi_matrix, col = rainbow(5))


image(simu1$pdd0_ndd1Var0.01Cut1_disp1_sr2_fbmr10_faoM$Output$`5000`$specMat, main = "ndd_5000")
image(simu1$pdd1Var0.01Cut1_ndd0_disp1_sr2_fbmr10_faoM$Output$`5000`$specMat, main = "pdd_5000")
image(simu1$pdd1Var0.01Cut1_ndd1Var0.01Cut1_disp1_sr2_fbmr10_faoM$Output$`5000`$specMat, main = "both_5000")
image(simu1$pdd0_ndd0_disp1_sr2_fbmr10_faoM$Output$`5000`$specMat, main = "none_5000")
image(simu1$pdd0_ndd0_dispG_sr2_fbmr10_faoM$Output$`5000`$specMat, main = "glob_5000")
image(easi_matrix, col = rainbow(5))


image(simu1$pdd0_ndd1Var0.01Cut1_disp1_sr2_fbmr10_faoM$Output$`5001`$specMat, main = "ndd_5001")
image(simu1$pdd1Var0.01Cut1_ndd0_disp1_sr2_fbmr10_faoM$Output$`5001`$specMat, main = "pdd_5001")
image(simu1$pdd1Var0.01Cut1_ndd1Var0.01Cut1_disp1_sr2_fbmr10_faoM$Output$`5001`$specMat, main = "both_5001")
image(simu1$pdd0_ndd0_disp1_sr2_fbmr10_faoM$Output$`5001`$specMat, main = "none_5001")
image(simu1$pdd0_ndd0_dispG_sr2_fbmr10_faoM$Output$`5001`$specMat, main = "glob_5001")
image(easi_matrix, col = rainbow(5))

```

## richness

```{r}
par(mfrow = c(2,3))
stats <- getSpecTime(simu1, ymax = 40, plot = T, title = c("nDD", "pDD", "both", "none", "global"))

cat("mean S in nDD run: ", mean(stats[[1]]$spec_rich))
cat("\nmean S in pDD run: ", mean(stats[[2]]$spec_rich))
cat("\nmean S in nDD+pDD run: ", mean(stats[[3]]$spec_rich))
cat("\nmean S in NULL run: ", mean(stats[[4]]$spec_rich))
cat("\nmean S in global run: ", mean(stats[[5]]$spec_rich))

cat("\n\nFor last 20 generations, mean S in nDD run: ", mean(stats[[1]]$spec_rich[80:100]))
cat("\nFor last 20 generations, mean S in pDD run: ", mean(stats[[2]]$spec_rich[80:100]))
cat("\nFor last 20 generations, mean S in nDD+pDD run: ", mean(stats[[3]]$spec_rich[80:100]))
cat("\nFor last 20 generations, mean S in NULL run: ", mean(stats[[4]]$spec_rich[80:100]))
cat("\nFor last 20 generations, mean S in global run: ", mean(stats[[5]]$spec_rich[80:100]))
```

## sac

```{r}
# positively bent curve (concave up) = clustering 
# negatively bent curve (concave down) = more neutral distribution
par(mfrow = c(2,3))

sac(runs = simu1, nested = TRUE,
    title = c("nDD", "pDD", "both", "none", "global"),
    rep = 500, size = c(1,seq(0,50,5)[-1]))

```

```{r}
par(mfrow = c(2,3))

rac(runs = simu1, ymax = 2000, xmax = 25, title = c("nDD", "pDD", "both", "none", "global"), plot_type = "line")
```

# density dependence

```{r}
simuCon1 <- getConNeigh(simu = simu1)
```

```{r}
par(mfrow= c(2,3), mar=c(2,2,2,2))

image(simuCon1$pdd0_ndd1Var0.01Cut1_disp1_sr2_fbmr10_faoM$Output$`101`$specMat, main = "ndd_101 spec")
image(simuCon1$pdd0_ndd1Var0.01Cut1_disp1_sr2_fbmr10_faoM$Output$`101`$conNeighMat, main = "ndd_101 conN")
image(simuCon1$pdd0_ndd1Var0.01Cut1_disp1_sr2_fbmr10_faoM$Output$`101`$mortMat, main = "ndd_101 mort",
      col = heat.colors(2))

image(simuCon1$pdd0_ndd1Var0.01Cut1_disp1_sr2_fbmr10_faoM$Output$`5000`$specMat, main = "ndd_5000 spec")
image(simuCon1$pdd0_ndd1Var0.01Cut1_disp1_sr2_fbmr10_faoM$Output$`5000`$conNeighMat, main = "ndd_5000 conN")
image(simuCon1$pdd0_ndd1Var0.01Cut1_disp1_sr2_fbmr10_faoM$Output$`5000`$mortMat, main = "ndd_5000 mort",
      col = heat.colors(2))
```

## get matrix to table

```{r}
simuTab <- getMatToTab(simuCon1, detailedParams = TRUE)
saveRDS(simuTab, "~/Uni/Master/MA/local/runs/others/demoTab.rds")
# simuTab1 <- readRDS(paste0(root, "/local/runs/others/demoTab.rds"))
# simuTab2 <- readRDS(paste0(root, "/local/runs/others/demoTab1.rds"))
```

```{r}
row.names(x = simuTab1) <- NULL # because too long 

simuTab1 <- simuTab1 %>%
  filter(census %% 2 == 0) # only analyse status at beginning of census

head(simuTab1)
tail(simuTab1)
```

# statistical model

```{r}
# filter all runs
simuNDD <- simuTab1 %>% filter(nDD == 1 & pDD == 0 & disp == 1)
simuPDD <- simuTab1 %>% filter(nDD == 0 & pDD == 1 & disp == 1)
simuNull <- simuTab1 %>% filter(nDD == 0 & pDD == 0 & disp == 1)
simuBoth <- simuTab1 %>% filter(nDD == 1 & pDD == 1 & disp == 1)
simuGlob <- simuTab1 %>% filter(disp == "global")

datasets1 <- list(
  simuNDD,
  simuPDD,
  simuNull,
  simuBoth,
  simuGlob
)

```

```{r}

# Function to calculate mortality change
calc_mortChange <- function(data) {
  fm <- glm("mortNextGen ~ con", family = "binomial", data = data)
  int <- fm$coefficients["(Intercept)"]
  est <- fm$coefficients["con"]
  mortChange <- plogis((int + est)) - plogis(int) # logit link
  return(mortChange)
}

# Apply function to each dataset
mortChanges1 <- sapply(datasets1, calc_mortChange)

# Display results

plot(y = mortChanges1, x = 1:5, xaxt = "n")
# points(y = mortChanges2, x = 1:5, xaxt = "n", pch = 2) # replicate
axis(1, at = 1:5, labels = c("NDD", "PDD", "Null", "Both", "Global"))
abline( h = 0)
```

